name = "paylink"
main = "src/index.js"
compatibility_date = "2025-06-01"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "paylink-db"
database_id = "ff70be73-57c2-472a-9284-0b9ea0bb537f"

[vars]
SITE_NAME = "PayLink"
INVOICE_TTL_MINUTES = "15"
APK_URL = "https://github.com/lagadev/uglypayapk/releases/download/v1.0.0/app-debug.apk"
SUPPORT_TELEGRAM = ""
